baseurl = "https://vietopeninfra.github.io/"
title = "ServiceMesher"
theme = "hugo-universal-theme"
languageCode = "zh"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "vn"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Code highlight
pygmentsUseClasses = false
pygmentCodeFences = true


[author]
    name = "adrianmo"
    homepage = "//github.com/adrianmo"

# If Porting existing theme
[original]
    author =  "bootstrapious"
    homepage = "http://bootstrapious.com/p/universal-business-e-commerce-template"
